[[redirects]]
from = "https://live.localheroesonline.com/oauth/google/*"
to = "com.LHConsumerApp.live://:splat"

[[redirects]]
from = "https://live.localheroesonline.com/oauth/google"
to = "com.LHConsumerApp.live://"

[[redirects]]
from = "https://staging.localheroesonline.com/oauth/google/*"
to = "com.LHConsumerApp.test://:splat"

[[redirects]]
from = "https://dev.localheroesonline.com/oauth/google/*"
to = "com.LHConsumerApp.dev://:splat"

