[[redirects]]
from = "/oauth/google/*"
to = "com.LHConsumerApp.live://:splat"
status = 302

[[redirects]]
from = "/oauth/google*"
to = "com.LHConsumerApp.live://:splat"
status = 302

#[[redirects]]
#from = "/*"
#to = "https://www.localheroesonline.com"
#status = 302

